defmodule Chisel.Font.BDF.LexerTest do
  use ExUnit.Case

  alias Chisel.Font.BDF.Lexer

  test "scan!/1" do
    assert [
             {:keyword, "STARTFONT", {1, 10}},
             {:value, "2.1", {1, 14}},
             {:eol, "\n", {1, 14}},
             {:keyword, "COMMENT", {2, 8}},
             {:value, "Lorem", {2, 14}},
             {:value, "ipsum", {2, 20}},
             {:value, "dolor", {2, 26}},
             {:value, "set", {2, 30}},
             {:eol, "\n", {2, 30}},
             {:keyword, "FONT", {3, 5}},
             {:value, "simple_font", {3, 17}},
             {:eol, "\n", {3, 17}},
             {:keyword, "SIZE", {4, 5}},
             {:value, "8", {4, 7}},
             {:value, "72", {4, 10}},
             {:value, "72", {4, 13}},
             {:eol, "\n", {4, 13}},
             {:value, "COPYRIGHT", {5, 10}},
             {:value, "©", {5, 13}},
             {:eol, "\n", {5, 14}},
             {:eol, "\n", {6, 1}},
             {:keyword, "CHARS", {7, 6}},
             {:value, "2", {7, 8}},
             {:eol, "\n", {7, 8}},
             {:keyword, "STARTCHAR", {8, 10}},
             {:value, "C1", {8, 13}},
             {:eol, "\n", {8, 13}},
             {:keyword, "ENCODING", {9, 9}},
             {:value, "128", {9, 13}},
             {:eol, "\n", {9, 13}},
             {:keyword, "DWIDTH", {10, 7}},
             {:value, "8", {10, 9}},
             {:value, "0", {10, 11}},
             {:eol, "\n", {10, 11}},
             {:keyword, "BBX", {11, 4}},
             {:value, "2", {11, 6}},
             {:value, "8", {11, 8}},
             {:value, "3", {11, 10}},
             {:value, "0", {11, 12}},
             {:eol, "\n", {11, 12}},
             {:keyword, "BITMAP", {12, 7}},
             {:eol, "\n", {12, 7}},
             {:value, "FF", {13, 3}},
             {:eol, "\n", {13, 3}},
             {:value, "FF", {14, 3}},
             {:eol, "\n", {14, 3}},
             {:value, "FF", {15, 3}},
             {:eol, "\n", {15, 3}},
             {:value, "FF", {16, 3}},
             {:eol, "\n", {16, 3}},
             {:value, "FF", {17, 3}},
             {:eol, "\n", {17, 3}},
             {:value, "FF", {18, 3}},
             {:eol, "\n", {18, 3}},
             {:value, "FF", {19, 3}},
             {:eol, "\n", {19, 3}},
             {:value, "FF", {20, 3}},
             {:eol, "\n", {20, 3}},
             {:keyword, "ENDCHAR", {21, 8}},
             {:eol, "\n", {21, 8}},
             {:eol, "\n", {22, 1}},
             {:keyword, "STARTCHAR", {23, 10}},
             {:value, "C2", {23, 13}},
             {:eol, "\n", {23, 13}},
             {:keyword, "ENCODING", {24, 9}},
             {:value, "129", {24, 13}},
             {:eol, "\n", {24, 13}},
             {:keyword, "DWIDTH", {25, 7}},
             {:value, "8", {25, 9}},
             {:value, "0", {25, 11}},
             {:eol, "\n", {25, 11}},
             {:keyword, "BBX", {26, 4}},
             {:value, "8", {26, 6}},
             {:value, "2", {26, 8}},
             {:value, "0", {26, 10}},
             {:value, "3", {26, 12}},
             {:eol, "\n", {26, 12}},
             {:keyword, "BITMAP", {27, 7}},
             {:eol, "\n", {27, 7}},
             {:value, "FF", {28, 3}},
             {:eol, "\n", {28, 3}},
             {:value, "FF", {29, 3}},
             {:eol, "\n", {29, 3}},
             {:keyword, "ENDCHAR", {30, 8}},
             {:eol, "\n", {30, 8}},
             {:keyword, "ENDFONT", {31, 8}},
             {:eol, "\n", {31, 8}}
           ] ==
             file_stream!("test/fixtures/simple.bdf")
             |> Lexer.scan!()
             |> Enum.to_list()
  end

  defp file_stream!(filename) do
    File.stream!(filename)
  end
end
